name: deploy
on:
  push:
    branches: ['main', '!all-contributors/**']
  pull_request:
    branches-ignore: ['all-contributors/**']

env:
  REMIX_TOKEN: ${{ secrets.REMIX_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: ⎔ Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: ▶️ Run validate script
        run: npx kcd-scripts validate

      - name: 🐳 Docker compose
        run: docker-compose up -d && sleep 3 && prisma migrate reset --force
        env:
          DATABASE_URL: 'postgresql://kody:the_koala@localhost:5432/kentcdodds_db?schema=public'

      - name: 🌳 Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run start:mocks
          wait-on: 'http://localhost:8811'
        env:
          PORT: '8811'
          RUNNING_E2E: 'true'
          DATABASE_URL: 'postgresql://kody:the_koala@localhost:5432/kentcdodds_db?schema=public'
          DOMAIN_URL: 'http://localhost:8811'

      - name: 🚀 Deploy
        # only deploy main branch on pushes
        if:
          ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        uses: superfly/flyctl-actions@1.1
        with:
          args: 'deploy --build-arg REMIX_TOKEN=${{ secrets.REMIX_TOKEN }}'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
