name: validate
on:
  push:
    branches: ['main', '!all-contributors/**']
  pull_request:
    branches-ignore: ['all-contributors/**']
env:
  REMIX_TOKEN: ${{ secrets.REMIX_TOKEN }}
  MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
  MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
  BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
  TITO_API_SECRET: ${{ secrets.TITO_API_SECRET }}
  FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
  SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: ⎔ Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: ▶️ Run validate script
        run: npx kcd-scripts validate test,lint,typecheck

      - name: ⬆️ Upload coverage report
        uses: codecov/codecov-action@v1

      - name: 🌳 Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: 'http://localhost:8811'
        env:
          PORT: 8811

      - name: 🚀 Deploy
        # only deploy main branch on pushes
        if:
          ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        uses: akhileshns/heroku-deploy@v3.6.8
        env:
          # "HD_" is removed by akhileshns/heroku-deploy
          # from the docs:
          # > so the action can tell your environment variable apart
          # > from multiple other variables (passed by your language,
          # > github actions etc) which you probably don't want sitting
          # > in your heroku app's config vars.
          HD_REMIX_TOKEN: ${{ secrets.REMIX_TOKEN }}
          HD_CYPRESS_INSTALL_BINARY: '0'
          HD_HUSKY_SKIP_INSTALL: '1'
          HD_MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          HD_MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
          HD_BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          HD_TITO_API_SECRET: ${{ secrets.TITO_API_SECRET }}
          HD_FIREBASE_SERVICE_ACCOUNT_KEY:
            ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          HD_SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: kentcdodds-remix
          heroku_email: me@kentcdodds.com
